/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/organisms/AppFooter.vue')['default']
    AuthenticationLayout: typeof import('./components/layouts/AuthenticationLayout.vue')['default']
    Button: typeof import('./components/atoms/Button.vue')['default']
    DashboardFooter: typeof import('./components/organisms/DashboardFooter.vue')['default']
    DashboardHeader: typeof import('./components/organisms/DashboardHeader.vue')['default']
    DashboardLayout: typeof import('./components/layouts/DashboardLayout.vue')['default']
    DashboardSidebar: typeof import('./components/organisms/DashboardSidebar.vue')['default']
    Default: (typeof import('./components/templates/default.vue'))['default']
    ExampleComponent: typeof import('./components/atoms/ExampleComponent.vue')['default']
    HelloWorld: typeof import('./components/organisms/HelloWorld.vue')['default']
    InputField: typeof import('./components/atoms/InputField.vue')['default']
    LoginForm: typeof import('./components/molecules/LoginForm.vue')['default']
    PasswordResetForm: typeof import('./components/molecules/PasswordResetForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleThemeButton: typeof import('./components/atoms/ToggleThemeButton.vue')['default']
    UserActions: typeof import('./components/organisms/UserActions.vue')['default']
    UserInfoPanel: typeof import('./components/organisms/UserInfoPanel.vue')['default']
  }
}
