/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/organinsms/AppFooter.vue')['default']
    Default: typeof import('./components/templates/default.vue')['default']
    ExampleComponent: typeof import('./components/atoms/ExampleComponent.vue')['default']
    HelloWorld: typeof import('./components/organinsms/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
